简单:
  - 梳理文章脉络
  - 信息提取与概括
  - 内容理解与概括
  - 词语理解与赏析：词语指代
  - 句子理解与赏析：句子赏析
一般:
  - 原因分析
  - 词语理解与赏析：词语含义
  - 词语理解与赏析：词语表达效果
  - 句子理解与赏析：句子含义
  - 句段作用：句子作用
  - 句段作用：段落作用
  - 标题理解与赏析
  - 细节描写
  - 环境描写
  - 表现手法
  - 叙述视角及人称作用
  - 记叙顺序
  - 揣摩人物心理
  - 把握人物情感变化
  - 概括分析人物形象
较难:
  - 朗读设计及情感
  - 探究文章主旨
  - 观点、启示和评价
  - 结合实践体验理解